services:
  - type: web
    name: flask-rag-app
    env: python
    region: oregon
    plan: free

    buildCommand: |
      pip install --upgrade pip && \
      pip install --only-binary=:all: --prefer-binary -r requirements.txt || \
      (echo "Failed with wheels, falling back..." && pip install -r requirements.txt)

    startCommand: python app.py

    envVars:
      - key: CERABRAS_API_KEY
        sync: false

    preDeployCommand: |
      echo "Cleaning bad packages..." && \
      sed -i '/pywin32/d' requirements.txt || true && \
      sed -i '/maturin/d' requirements.txt || true && \
      sed -i '/pyo3/d' requirements.txt || true