services:
  - type: web
    name: flask-rag-app
    env: python
    region: oregon
    plan: free

    # FORCE Python 3.11 — this is the key
    buildCommand: |
      python3.11 -m venv $VIRTUAL_ENV && \
      pip install --upgrade pip && \
      pip install --only-binary=:all: -r requirements.txt

    startCommand: python app.py

    envVars:
      - key: CEREBRAS_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: rag-postgres
          property: connectionString

    preDeployCommand: |
      echo "Cleaning Rust build tools..." && \
      sed -i '/ninja/d' requirements.txt || true && \
      sed -i '/maturin/d' requirements.txt || true && \
      sed -i '/pyo3/d' requirements.txt || true && \
      sed -i '/setuptools-rust/d' requirements.txt || true