services:
  - type: web
    name: flask-rag-app
    env: python
    region: oregon
    plan: free

    buildCommand: |
      pip install --upgrade pip && \
      pip install --only-binary=:all: -r requirements.txt

    startCommand: python app.py

    envVars:
      - key: CEREBRAS_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: rag-postgres
          property: connectionString