services:
  - type: web
    name: flask-rag-app
    env: python
    pythonVersion: "3.11"        # ← THIS IS CRITICAL
    region: oregon
    plan: free

    buildCommand: |
      pip install --upgrade pip && \
      pip install --only-binary=:all: -r requirements.txt

    startCommand: python app.py

    envVars:
      - key: CEREBRAS_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: rag-postgres
          property: connectionString

    preDeployCommand: |
      echo "Removing Rust build tools..." && \
      sed -i '/ninja/d' requirements.txt || true && \
      sed -i '/maturin/d' requirements.txt || true && \
      sed -i '/pyo3/d' requirements.txt || true && \
      sed -i '/setuptools-rust/d' requirements.txt || true