services:
  - type: web
    name: flask-rag-app
    env: docker  # ← KEY: Use Docker runtime
    region: oregon
    plan: free

    dockerfilePath: ./Dockerfile  # ← Points to your Dockerfile

    startCommand: python app.py

    envVars:
      - key: CEREBRAS_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: rag-postgres
          property: connectionString